services:
  mysql-dev:
    image: mysql:latest
    container_name: flask-db
    # Requires root password to be set
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports: 
      - 6603:3306
    volumes:
      # volume to hold the database related files
      - database-folder:/var/lib/mysql
      # inserts sql script to run on start up
      - ./DB/users.sql:/docker-entrypoint-initdb.d/users.sql
  python-dev:
    container_name: flask-server
    # container will restart if there is an error or major problem
    restart: always
    build: 
      # hands the build command the relative 
      # file position based on the current directory
      context: ./
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/var/app/flask_app
    ports:
      - "8000:8000"
  adminer:
    image: adminer
    container_name: flask-adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql-dev
volumes:
  database-folder: 