services:
  python-dev:
    container_name: flask-server
    build: 
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/app/flask_app
    ports:
      - "8000:8000"
  mysql-dev:
    build: ./DB/
    container_name: mysql-db-container
    ports: 
      - 6603:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "root" # set and remove password. Dont push
    volumes:
      - /storage/docker/mysql-datadirectory/:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer-tool
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql-dev
  volumes:
    database-folder: